name: final_projesi
description: "A new Flutter project."
publish_to: 'none'
version: 0.1.0

environment:
  sdk: ^3.5.3

dependencies:
  flutter:
    sdk: flutter
  google_fonts: ^6.2.1
  image_picker: ^0.8.6+3
  flutter_rating_bar: ^4.0.1
  sqflite: ^2.4.1
  path: ^1.9.0
  path_provider: ^2.0.15 

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^4.0.0
  flutter_launcher_icons: ^0.13.1

flutter:
  uses-material-design: true
  assets:
    - assets/
    - assets/three_kingdoms.jpg
    - assets/dune.jpg
    - assets/red_rising.jpg

flutter_launcher_icons:
  android: "launcher_icon"
  ios: true
  image_path: "assets/icon.png"